using System;
using Theming;
using UnityEngine;

namespace InternalTheming
{
    public static class ColorConverter
    {
        // Get color by app theme and marker (Connect fields with colors and enum items)
        public static Color GetColor(ITheme theme, ColorTheme color)
        {
            switch (color)
            {
                case ColorTheme.StatusBar:
                    return theme.StatusBar;
                case ColorTheme.PrimaryColor:
                    return theme.PrimaryColor;
                case ColorTheme.WorkAreaYearText:
                    return theme.WorkAreaYearText;
                case ColorTheme.YearStatsOutline:
                    return theme.YearStatsOutline;
                case ColorTheme.YearStatsBackground:
                    return theme.YearStatsBackground;
                case ColorTheme.WorkAreaFlowCircle:
                    return theme.WorkAreaFlowCircle;
                case ColorTheme.WorkAreaLines:
                    return theme.WorkAreaLines;
                case ColorTheme.WorkAreaFlowText:
                    return theme.WorkAreaFlowText;
                case ColorTheme.WorkAreaFlowTextStats:
                    return theme.WorkAreaFlowTextStats;
                case ColorTheme.SecondaryColor:
                    return theme.SecondaryColor;
                case ColorTheme.WorkAreaBackground:
                    return theme.WorkAreaBackground;
                case ColorTheme.WorkAreaFlowHandle:
                    return theme.WorkAreaFlowHandle;
                case ColorTheme.TrackAreaBlackout:
                    return theme.TrackAreaBlackout;
                case ColorTheme.TrackAreaMain:
                    return theme.TrackAreaMain;
                case ColorTheme.TrackAreaMainSecondary:
                    return theme.TrackAreaMainSecondary;
                case ColorTheme.TrackAreaSplitLine:
                    return theme.TrackAreaSplitLine;
                case ColorTheme.TrackAreaHandleLine:
                    return theme.TrackAreaHandleLine;
                case ColorTheme.SecondaryColorD2:
                    return theme.SecondaryColorD2;
                case ColorTheme.SecondaryColorD3:
                    return theme.SecondaryColorD3;
                case ColorTheme.TrackAreaFlowTitle:
                    return theme.TrackAreaFlowTitle;
                case ColorTheme.TrackAreaCalendar:
                    return theme.TrackAreaCalendar;
                case ColorTheme.TrackFlowItems:
                    return theme.TrackFlowAreaItems;
                case ColorTheme.MenuAreaButtons:
                    return theme.MenuAreaButtons;
                case ColorTheme.MenuAreaSplitLine:
                    return theme.MenuAreaSplitLine;
                case ColorTheme.MenuAreaFlowNameLine:
                    return theme.MenuAreaFlowNameLine;
                case ColorTheme.MenuAreaFlowNamePlaceholder:
                    return theme.MenuAreaFlowNamePlaceholder;
                case ColorTheme.MenuAreaFlowNameText:
                    return theme.MenuAreaFlowNameText;
                case ColorTheme.MenuAreaFlowIconBackground:
                    return theme.MenuAreaFlowIconBackground;
                case ColorTheme.CreateFlowAreaTitle:
                    return theme.CreateFlowAreaTitle;
                case ColorTheme.CreateFlowAreaDescription:
                    return theme.CreateFlowAreaDescription;
                case ColorTheme.RemindersModuleSplitLine:
                    return theme.RemindersModuleSplitLine;
                case ColorTheme.RemindersModuleDays:
                    return theme.RemindersModuleDays;
                case ColorTheme.SecondaryColorD1:
                    return theme.SecondaryColorD1;
                case ColorTheme.RemindersModuleButtonBackground:
                    return theme.RemindersModuleButtonBackground;
                case ColorTheme.CreateFlowAreaTypeIcons:
                    return theme.CreateFlowAreaTypeIcons;
                case ColorTheme.DefaultBackgroundColor:
                    return theme.DefaultBackgroundColor;
                case ColorTheme.CreateFlowAreaTypeText:
                    return theme.CreateFlowAreaTypeText;
                case ColorTheme.ViewFlowAreaTitle:
                    return theme.ViewFlowAreaTitle;
                case ColorTheme.ViewFlowAreaDescription:
                    return theme.ViewFlowAreaDescription;
                case ColorTheme.CreateFlowAreaButtonTextElements:
                    return theme.CreateFlowAreaButtonTextElements;
                case ColorTheme.ImagesColor:
                    return theme.ImagesColor;
                case ColorTheme.SecondaryColorP1:
                    return theme.SecondaryColorP1;
                case ColorTheme.SecondaryColorP2:
                    return theme.SecondaryColorP2;
                case ColorTheme.SecondaryColorD4:
                    return theme.SecondaryColorD4;
                case ColorTheme.EditFlowChosenType:
                    return theme.EditFlowChosenType;
                case ColorTheme.CalendarItemActive:
                    return theme.CalendarItemActive;
                case ColorTheme.CalendarItemActiveOut:
                    return theme.CalendarItemActiveOut;
                case ColorTheme.CalendarItemPassive:
                    return theme.CalendarItemPassive;
                case ColorTheme.ActivityFrequencyDays:
                    return theme.ActivityFrequencyDays;
                case ColorTheme.CalendarModuleWeeks:
                    return theme.CalendarModuleWeeks;
                case ColorTheme.CalendarCapBackground:
                    return theme.CalendarCapBackground;
                case ColorTheme.EditGroupInputBackground:
                    return theme.EditGroupInputBackground;
                case ColorTheme.UpdateIconModuleTitle:
                    return theme.UpdateIconModuleTitle;
                case ColorTheme.PrimaryColorP1:
                    return theme.PrimaryColorP1;
                case ColorTheme.ActivityWeekSplitLine:
                    return theme.ActivityWeekSplitLine;
                case ColorTheme.ActivityWeekDayDefault:
                    return theme.ActivityWeekDayDefault;
                case ColorTheme.WorkAreaWeeklyBorders:
                    return theme.WorkAreaWeeklyBorders;
                case ColorTheme.ActivityYear:
                    return theme.ActivityYear;
                case ColorTheme.EmptyDescriptionText:
                    return theme.EmptyDescriptionText;
                case ColorTheme.SecondaryColorD4A50:
                    return theme.SecondaryColorD4A50;
                case ColorTheme.DaysMarkerAreaDaysColor:
                    return theme.DaysMarkerAreaDaysColor;
                case ColorTheme.DaysMarkerAreaYear:
                    return theme.DaysMarkerAreaYear;
                case ColorTheme.DaysMarkerAreaYearArrow:
                    return theme.DaysMarkerAreaYearArrow;
                case ColorTheme.DaysMarkerAreaMarkerMonthTitle:
                    return theme.DaysMarkerAreaMarkerMonthTitle;
                case ColorTheme.DaysMarkerAreaMarkerMonthSliderBackground:
                    return theme.DaysMarkerAreaMarkerMonthSliderBackground;
                case ColorTheme.DaysMarkerAreaModuleSplitLine:
                    return theme.DaysMarkerAreaModuleSplitLine;
                case ColorTheme.DaysMarkerAreaModuleMarkerNameEmpty:
                    return theme.DaysMarkerAreaModuleMarkerNameEmpty;
                case ColorTheme.DaysMarkerAreaModuleDayNameEmpty:
                    return theme.DaysMarkerAreaModuleDayNameEmpty;
                case ColorTheme.DaysMarkerAreaModuleDayNameDisabled:
                    return theme.DaysMarkerAreaModuleDayNameDisabled;
                case ColorTheme.DaysMarkerAreaModuleMarkerNameDisabled:
                    return theme.DaysMarkerAreaModuleMarkerNameDisabled;
                case ColorTheme.DaysMarkerAreaTipText:
                    return theme.DaysMarkerAreaTipText;
                case ColorTheme.TutorialText:
                    return theme.TutorialText;
                case ColorTheme.SettingsUnlock:
                    return theme.SettingsUnlock;
                case ColorTheme.SettingsUnlockArrow:
                    return theme.SettingsUnlockArrow;
                case ColorTheme.WorkAreaBackgroundShadow:
                    return theme.WorkAreaBackgroundShadow;
                case ColorTheme.AppBarShadow:
                    return theme.AppBarShadow;
                case ColorTheme.WorkAreaBackgroundImage:
                    return theme.WorkAreaBackgroundImage;
                case ColorTheme.WorkAreaFlowHandleShadow:
                    return theme.WorkAreaFlowHandleShadow;
                case ColorTheme.AppBarElements:
                    return theme.AppBarElements;
                case ColorTheme.ActivityWeekDayActive:
                    return theme.ActivityWeekDayActive;
                case ColorTheme.ActivityDayPreviewDonePassive:
                    return theme.ActivityDayPreviewDonePassive;
                case ColorTheme.ActivityResultDonePassive:
                    return theme.ActivityResultDonePassive;
                case ColorTheme.CalendarMonthPassive:
                    return theme.CalendarMonthPassive;
                case ColorTheme.CalendarMonthActive:
                    return theme.CalendarMonthActive;
                case ColorTheme.TrackFlowAreaCalendarIcon:
                    return theme.TrackFlowAreaCalendarIcon;
                case ColorTheme.EditGroupTextInput:
                    return theme.EditGroupTextInput;
                case ColorTheme.EditGroupNavigationPassive:
                    return theme.EditGroupNavigationPassive;
                case ColorTheme.EditGroupIconCirclePassive:
                    return theme.EditGroupIconCirclePassive;
                case ColorTheme.EditGroupPlaceholder:
                    return theme.EditGroupPlaceholder;
                case ColorTheme.EditGroupSelection:
                    return theme.EditGroupSelection;
                case ColorTheme.MenuAreaButtonName:
                    return theme.MenuAreaButtonName;
                case ColorTheme.MenuAreaButtonIcon:
                    return theme.MenuAreaButtonIcon;
                case ColorTheme.MenuAreaButtonIconAdditional:
                    return theme.MenuAreaButtonIconAdditional;
                case ColorTheme.TipsText:
                    return theme.TipsText;
                case ColorTheme.ChooseItemPanelCirclePassive:
                    return theme.ChooseItemPanelCirclePassive;
                case ColorTheme.ActivityFlowInProgressGoal:
                    return theme.ActivityFlowInProgressGoal;
                case ColorTheme.ViewFlowAreaInProgressGoal:
                    return theme.ViewFlowAreaInProgressGoal;
                case ColorTheme.ViewFlowAreaInProgressPercentage:
                    return theme.ViewFlowAreaInProgressPercentage;
                case ColorTheme.ViewFlowAreaRemindersCirclePassive:
                    return theme.ViewFlowAreaRemindersCirclePassive;
                case ColorTheme.ViewFlowAreaRemindersIconPassive:
                    return theme.ViewFlowAreaRemindersIconPassive;
                case ColorTheme.ViewFlowAreaRemindersDayPassive:
                    return theme.ViewFlowAreaRemindersDayPassive;
                case ColorTheme.ViewFlowAreaRemoveButton:
                    return theme.ViewFlowAreaRemoveButton;
                case ColorTheme.TipsModuleSplitLine:
                    return theme.TipsModuleSplitLine;
                case ColorTheme.ChooseItemPanelDonePassive:
                    return theme.ChooseItemPanelDonePassive;
                case ColorTheme.UpdateArchivedFlowModuleRemoveLoad:
                    return theme.UpdateArchivedFlowModuleRemoveLoad;
                case ColorTheme.UpdateArchivedFlowModuleRemoveCircle:
                    return theme.UpdateArchivedFlowModuleRemoveCircle;
                case ColorTheme.DaysMarkerAreaMonthDayCirclePassive:
                    return theme.DaysMarkerAreaMonthDayCirclePassive;
                case ColorTheme.DaysMarkerAreaMonthDayCircleDisabled:
                    return theme.DaysMarkerAreaMonthDayCircleDisabled;
                case ColorTheme.DaysMarkerAreaPickerEmptyColor:
                    return theme.DaysMarkerAreaPickerEmptyColor;
                case ColorTheme.DaysMarkerAreaUpdateMarkerInput:
                    return theme.DaysMarkerAreaUpdateMarkerInput;
                case ColorTheme.DaysMarkerAreaUpdateMarkerPlaceholder:
                    return theme.DaysMarkerAreaUpdateMarkerPlaceholder;
                case ColorTheme.FlowViewAreaIconImage:
                    return theme.FlowViewAreaIconImage;
                case ColorTheme.CreateFlowAreaContentCircles:
                    return theme.CreateFlowAreaContentCircles;
                case ColorTheme.CreateFlowAreaContentIcon:
                    return theme.CreateFlowAreaContentIcon;
                case ColorTheme.WorkAreaBackgroundImageCircle:
                    return theme.WorkAreaBackgroundImageCircle;
                case ColorTheme.SettingsLockIcon:
                    return theme.SettingsLockIcon;
                case ColorTheme.StatisticsAreaBackgroundImage:
                    return theme.StatisticsAreaBackgroundImage;
                case ColorTheme.LoadBackupModuleDescription:
                    return theme.LoadBackupModuleDescription;
                case ColorTheme.SettingsUnlockThanks:
                    return theme.SettingsUnlockThanks;
                case ColorTheme.PurchasePageBottomText:
                    return theme.PurchasePageBottomText;
                case ColorTheme.ThanksItemName:
                    return theme.ThanksItemName;
                case ColorTheme.PurchaseRestoreText:
                    return theme.PurchaseRestoreText;
                default:
                    throw new ArgumentOutOfRangeException(nameof(color), color, null);
            }
        }
    }
}
